### ISSUE TITLE
version-number output is empty

### ISSUE THREAD

**Issue by Piedone** [timheuer/vsix-version-stamp#1]
The `version-number` output is empty. See e.g. [this code](https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/blob/60abc9bf461dfe788c988d696fbbe6d63aaa5ceb/.github/workflows/build.yml#L36) that results in [this output](https://github.com/Lombiq/Lombiq-Orchard-Visual-Studio-Extension/actions/runs/3456852647/jobs/5769884596#step:5:5).

**Comment by timheuer** [comment]
Hi @all-contributors please add @Piedone for bug, code, ideas
